### ISSUE TITLE
win32 version Output Height setting failed 

### ISSUE THREAD

**Issue by mosquito520** [zint/zint-gpl-only#12]
Hi all:)
I'm using Win32 version,
and I've change Height field value to 100 ,in Appearance tab, 
But when I press Save to specific a Path to save picture,
and choose output type to PNG, Then press Save button,
output picture resolution is still 46x46.

Please help to modify it:)

Best regards.
Mosquito

**Comment by gitlost** [comment]
Hi, thanks for your feedback. This fork is no longer in use and I think this issue is fixed with the latest version of Zint so am closing now. If the issue does persist or if you have any other feedback please raise a ticket at https://sourceforge.net/p/zint/tickets/, thanks.
