### ISSUE TITLE
Zint does not compile with libPNG under Windows

### ISSUE THREAD

**Issue by patlecat** [zint/zint-gpl-only#18]
I use the latest mingw64 with gcc 4.7.2 with cmake 2.8.10 under Windows 8 and successfully built zlib 1.2.7 and libpng 1.5.13. I added both folders to the PATH. But zint claimed not being able to find png.h. Qt4 is not installed on my system.

**Comment by gitlost** [comment]
Hi, this fork is no longer in use. If this issue persists, please raise a ticket at https://sourceforge.net/p/zint/tickets/, thanks.
