### ISSUE TITLE
PDF Error

### ISSUE THREAD

**Issue by boom0192** [zint/zint-gpl-only#19]
I think the PDF section 6.6.2 QR Code (ISO 18004) should say secure= not security=, see below for what it currently says.
Also known as Quick Response Code this symbology was developed by Denso.
Four levels of error correction are available using the security= option or setting
option_1 as shown in the following table.

**Comment by gitlost** [comment]
Hi, thanks for the feedback. The latest version of the manual has your corrections, so closing this. If you've any further feedback please raise a ticket at https://sourceforge.net/p/zint/tickets/.
