### ISSUE TITLE
No human readable text visible when using --scale

### ISSUE THREAD

**Issue by Max-Might** [zint/zint-gpl-only#21]
Hi.

I have a problem where the text below the barcode is not visible when I have used the --scale option.

In the zint GUI there is text but when the image is saved there is no human readable text.

**Comment by gitlost** [comment]
Hi, I've created a ticket for this at https://sourceforge.net/p/zint/tickets/261/. As this fork is no longer used, am closing this, but the issue remains. Thanks for the feedback.
