### ISSUE TITLE
php lib

### ISSUE THREAD

**Issue by mithrandirii** [zint/zint-gpl-only#23]
hi,

we created an php extension for zint lib. it can be used to generate a barcode to a file. it understands the most options of libzint and some error reporting. if you want, i can give you the code and you can integrate it into the project.

greetings

dominik

**Comment by delboy1978uk** [comment]
This is a command line tool, if you have a wrapper class for PHP, that's a separate project! Stick it on Github!

**Comment by mithrandirii** [comment]
zint is not only an command line tool. you can compile it as shared lib too. for the shared we created an native php lib. sadly this is not maintained any more but it is still on github: [mithrandirii/php-zint]

**Comment by mithrandirii** [comment]
btw the zint here at this repo is outdated! there is a much newer one on sourceforge: [zint](https://sourceforge.net/projects/zint/)

**Comment by gitlost** [comment]
Hi, we're very interested in a PHP extension for zint. Please submit a Merge Request at https://sourceforge.net/projects/zint/ if you're still interested in incorporating this in the main repository (perhaps as a subdirectory "backend_php" or similar). As this fork is no longer in use, am closing this now. Thanks.
