### ISSUE TITLE
[Bug] Wrong checkdigit for NVE18/EAN14

### ISSUE THREAD

**Issue by chaosben** [zint/zint-gpl-only#24]
Example: 2605
Barcode-Generator calcs "3" as checksum
Correct value (according to http://www.gs1.org/barcodes/support/check_digit_calculator ): "5"

Imho, its caused by the wrong condition in line 965 and 1006 of code128.c. 
The condition should be this one: if (!((length - 1 - i) & 1))

**Comment by gitlost** [comment]
This issue is now fixed in the latest version of Zint, so am closing now. Thanks for your feedback. Note that this fork is no longer used, see https://sourceforge.net/projects/zint/.
