### ISSUE TITLE
Incorrect AusPost 4-state barcoding?

### ISSUE THREAD

**Issue by onlyjob** [zint/zint-gpl-only#33]
With Zint I can't quite reproduce barcodes from the following manual:

http://auspost.com.au/media/documents/a-guide-to-printing-the-4state-barcode-v31-mar2012.pdf

Could it be a bug or is this particular (DPID) barcode subtype is not implemented?

A colleague of mine reported that he was unable to scan Australian 4-state barcodes generated by Zint...

**Comment by gitlost** [comment]
These examples are now reproducible in the latest version of Zint (and have been added to the test suite), thanks for the feedback, closing...
