### ISSUE TITLE
Please clarify status of this repository; please tag releases.

### ISSUE THREAD

**Issue by onlyjob** [zint/zint-gpl-only#34]
Could you please confirm whether my impression that development of Zint has been moved here from Sourceforge is accurate? Is this an official (authoritative) Zint repository? If so it would be nice to put a corresponding note to README (and perhaps to project page at Sourceforge).

Also I'd like to ask you to tag releases which is very helpful for automatic notifications for new releases as well as it allow to conveniently download Zint sources in compressed tarball.

By the way for the sake of best practice it would be nice to ship ChangeLog in top level directory rather than as "debian/changelog" which is meant for packaging-related news only.

Thank you.

**Comment by Elmi77** [comment]
@onlyjob: the most recent version of ZINT can be found at http://sourceforge.net/u/oehhar/zint/ci/master/tree/ meanwhile.

**Comment by gitlost** [comment]
This fork will be archived soon so am closing this issue.
