### ISSUE TITLE
Generate extended Barcode with an TAB command

### ISSUE THREAD

**Issue by if2s** [zint/zint-gpl-only#35]
Hello, is it possible (how to do that) to generate a barcode with some text, then a TAB-command like the TAB-Key on keyboard and then other text?
What do I have to type in extended Code39 or Code128 to get e.g. following barcode:
User<-TAB->Password

**Comment by gitlost** [comment]
For Code 128 or Code 39 Extended you can use "User\tPassword" with `--esc` (or with the "Parse Escapes" checked in the GUI). This fork is no longer in use so am closing. If you have further questions, please subscribe to the SourceForge mailing list or raise a ticket at https://sourceforge.net/p/zint/tickets/, thanks!
