### ISSUE TITLE
Missing document of ZBarcode_Render

### ISSUE THREAD

**Issue by xuhdev** [zint/zint-gpl-only#36]
I'm interested in how to render the barcode, but the document of this function is missing. Could you add the doc, please? Thanks!

**Comment by gitlost** [comment]
The current version of this is `ZBarcode_Buffer_Vector()` which is documented in the manual. If you've any further questions please raise a ticket at https://sourceforge.net/p/zint/tickets/ or subscribe to the mailing list at SourceForge, as this fork is no longer in use, thanks!
