### ISSUE TITLE
info: aztec encoding "Code 2D!"

### ISSUE THREAD

**Issue by Jonney3099** [zint/zint-gpl-only#41]
in specification ISO/IEC CD 24778.3, on Page 46 (Annex G:Aztec Code symbol encoding example), the string ”Code 2D!" encoding result is " 00100 11100 10000 00101 00110 11110 0001 0100 1111 00101 0000 00110" which is 56 digits due to Digit Latch  at Space Position. however, Zint's result is "00100 11100 10000 00101 00110 00001 11110 0100 1111 00101 0000 00110" which has 57 digits. Even though the scanner got the same result,but Zing encoding is not the shortest length. Can you improve aztec_text_process? Thanks.

**Comment by gitlost** [comment]
The current version of Zint produces the same code as the standard now (and there's a test case for it in the test suite). If you've any further feedback please raise a ticket at https://sourceforge.net/p/zint/tickets/ as this fork is no longer in use, thanks!
