### ISSUE TITLE
issue of RSS14 limit

### ISSUE THREAD

**Issue by zwd183335** [zint/zint-gpl-only#44]
when the checksum equal 88, check_elements[i] = finder_pattern_ltd[i + (checksum \* 14)]; ,index of finder_pattern_ltd will overflow.

**Comment by oehhar** [comment]
Fix is in:
https://sourceforge.net/p/zint/code/ci/fdbe0c633834cb4d3768f902abe3c08d239a8c5a/tree/

Thanks to Robin.
- Harald

**Comment by gitlost** [comment]
As this issue is fixed, am closing now. Thanks for the feedback, for further feedback please raise a ticket at https://sourceforge.net/p/zint/tickets/, thanks!
