### ISSUE TITLE
backend /gridmtx.c:247: bad if test ?

### ISSUE THREAD

**Issue by dcb314** [zint/zint-gpl-only#47]
backend/gridmtx.c:247:27: warning: logical 'and' of mutually exclusive tests is always 
false [-Wlogical-op]

  if((gbdata[sp] == 0x13) && (gbdata[sp] == 0x10)) {

**Comment by gitlost** [comment]
Hi the current logic in the latest version of Zint does not have this issue so am closing. For further feedback, please raise a ticket at https://sourceforge.net/p/zint/tickets/ as this fork is no longer in use, thanks!
