### ISSUE TITLE
What is the relationship between “printing scale”&“mil”

### ISSUE THREAD

**Issue by deepfish** [zint/zint-gpl-only#55]
I want to create a QR code which size is 20 mil. But  I don't know the relationship between  “printing scale”&“mil”. Could someone can tell me how to set the value . Thank  a  lot .

**Comment by gitlost** [comment]
The scale will depend on the resolution (DPI) that you wish to achieve. There's documentation on this in the manual (see "[docs/manual.txt](https://sourceforge.net/p/zint/code/ci/master/tree/docs/manual.txt#l1021)" Section 4.9 Adjusting Image Size). If you'd like further help, please raise a ticket at https://sourceforge.net/p/zint/tickets/ as this fork is no longer in use, thanks!
