### ISSUE TITLE
Builing zint on linux as static lib

### ISSUE THREAD

**Issue by bencz** [zint/zint-gpl-only#60]
Hi
How to build the zint as static lib to linking with the executable, on linux ?

**Comment by denisdemaisbr** [comment]
use libtool or ar

https://www.gnu.org/software/libtool/
http://www.manpagez.com/man/1/libtool/

http://www.network-theory.co.uk/docs/gccintro/gccintro_79.html
https://linux.die.net/man/1/ar

**Comment by tispratik** [comment]
Were you able to successfully build it on linux?

**Comment by bencz** [comment]
Nop... I just added all the source on my project....

**Comment by tispratik** [comment]
You mean you built it on linux as a part of your project?

**Comment by bencz** [comment]
Yeap... I just added all the zint source to my source project and used it :)

**Comment by tispratik** [comment]
Thanks for your quick response Alex!

**Comment by gitlost** [comment]
Note there is now a CMake option `ZINT_STATIC` to build zint as a static library in the latest version of Zint. As this fork is no longer in use, am closing this. If you've any further questions, please raise a ticket at https://sourceforge.net/p/zint/tickets/, thanks all!
