### ISSUE TITLE
Support for Swiss QR Code

### ISSUE THREAD

**Issue by simhof-basyskom** [zint/zint-gpl-only#61]
Hi, Switzerland will introduce a "special" Swiss QR Code (ISO-20022) as mandatory for bills in the future, see for example https://www.paymentstandards.ch/en/home/schemes/payment-slips.html.
The new code seems to be a standard QR Code just with a swiss flag symbol planted in the middle.

Could zint support the creation of such a code directly; or more generally add a method to overlay an image over the produced code?

**Comment by lukebranch** [comment]
@simhof-basyskom ,

I'm just a zint user here, so I don't speak with any authority, but I think you can just overlay the image over the top of the QR code. I believe that's the way it's done where i've seen it.

QR codes have a certain level of error/corruption tolerance, so the QR code will still work as long as you have this error tolerance setup to the correct level.

**Comment by simhof-basyskom** [comment]
@lukebranch , thanks. Yeah, I guess that should work fine.

On one hand an integrated solution would be nicer to use, on the other hand I can see why including only loosely related functionality into zint might not be the best of ideas.

So I'll leave this for the developers to decide and close (or implement) accordingly.

**Comment by oehhar** [comment]
Am 14.06.2017 um 14:50 schrieb Steffen Imhof:
> @lukebranch <https://github.com/lukebranch> , thanks. Yeah, I guess that
> should work fine.
> 
> On one hand an integrated solution would be nicer to use, on the other
> hand I can see why including only loosely related functionality into
> zint might not be the best of ideas.
> 
> So I'll leave this for the developers to decide and close (or implement)
> accordingly.

I suppose, the overlayed "+" in the code is not important. It is a
gimmick you can just leave out to increase reading performence and
reliability.

Another remark: you are using the github for comments.
If you really want to get attention from the developpers please use the
mailing list or the ticket system at sourceforge.

Thank you,
Harald

**Comment by gitlost** [comment]
Hi have opened a ticket for this at SourceForge https://sourceforge.net/p/zint/tickets/262/ so will close the issue here as this fork is no longer in use. Thanks for the feedback all.
