### ISSUE TITLE
Request: Default symbology

### ISSUE THREAD

**Issue by ghost** [zint/zint-gpl-only#63]
Hello,

would it be possible to add an option to set the default symbology upon opening Zint Barcode Studio?

For someone like me, who uses the program for QR codes only, it would make things a lot easier and faster.

Example: You open Zint Barcode Studio and "QR Code" is automatically selected.

Thank you for reading.

**Comment by mikemaikaefer** [comment]
This is not the original ZINT repository but an outdated fork only. Please refer to the original ZINT project at sourceforge.net!

**Comment by gitlost** [comment]
The latest version of Zint Barcode Studio re-opens the last symbology used so closing this.
