### ISSUE TITLE
codabar has issues with numbers

### ISSUE THREAD

**Issue by brettowe** [zint/zint-gpl-only#64]
trying to make a barcode with codabar with just numbers gives an error of invalid characters in data
using any android app scanning an existing barcode I'm hoping to reprint said it's codabar text and it's all numbers
I'm on Windows for the error, haven't tested Linux

**Comment by oehhar** [comment]
Dear Brettowe,

thank you for the message. A Codabar code always requires an A,B,C or D at the beginning or End.
So a Codabar with numbers only is an invalid code.

[](https://en.wikipedia.org/wiki/Codabar)

So, Android is right. If one can print this with zint, this is an error.

Please consider also to use zint on sourceforge including its bug-tracker.

Best regards,
Harald

**Comment by gitlost** [comment]
Hi the latest version of Zint insists on A/B/C/D at beginning/end so this issue should no longer arise. If you've any further questions please open a ticket at https://sourceforge.net/p/zint/tickets/, thanks.
