### ISSUE TITLE
Batch mode broken: file numbering not corresponding to line numbers, lines skipped

### ISSUE THREAD

**Issue by RipperFox** [zint/zint-gpl-only#65]
Thanks for this great piece of software - just a little issue I discovered with version 2.4.2.0 on Windows:

The filenames in batch mode are generated wrongly:

- Made a file with a number per line (1,2..10)
- Output parameter: -o ~~~~~.png
- 00001.png contains barcode of line 10  / content of line 1 is missing
- 00011.png contains barcode of line 10
- no file "00010.png" exists

Gets worse with more lines: With an input file with some thousand lines line 1000 was written to 00001.png - seems a problem of how the filename is put together.

Output of ####.png is wrong also, but different; the @ character doesn't work at all (maybe commandline issue/limitation on Windows)

Documentation states: "By default Zint will output numbered filenames starting with 00001.png
,00002.png etc. To change this behaviour use the ­o option..." but when "-o" is missing, only one file called "out.png" is (over-)written.
­­

**Comment by mikemaikaefer** [comment]
This is not the original ZINT repository but an outdated fork only. Please refer to the original ZINT project at sourceforge.net!

**Comment by gitlost** [comment]
Hi, thanks for reporting this. The current version doesn't seem to have the data/line problems you report, but as you say it doesn't default to producing "00001.png", "00002.png" etc. as documented. Also for Windows asterisk isn't allowed in filenames so fails. I've opened a ticket on SourceForge https://sourceforge.net/p/zint/tickets/263/ for these issues, please see that for further info. As this fork is no longer in use, am closing this, but the ticket on SourceForge will remain open until the next release for any further feedback you care to give. Thanks you.
