### ISSUE TITLE
Cleaner code

### ISSUE THREAD

**Issue by pasnox** [zint/zint-gpl-only#66]
Please ensure those defines are set when building the Qt front end to ensure no implicit convertion occurs in your code, leading to possible issues.

DEFINES *=
  QT_NO_CAST_FROM_BYTEARRAY \\
  QT_NO_CAST_FROM_ASCII \\
  QT_NO_CAST_TO_ASCII \\
  QT_NO_URL_CAST_FROM_STRING \\
  QT_STRICT_ITERATORS

**Comment by mikemaikaefer** [comment]
This is not the original ZINT repository but an outdated fork only. Please refer to the original ZINT project at sourceforge.net!

**Comment by gitlost** [comment]
Hi, the current code doesn't seem to suffer form the issues you mention but maybe your method is better than the suppression currently used. If you wish to suggest a Merge Request on [SourceForge](https://sourceforge.net/projects/zint/) it'd be considered carefully. Am closing this now as this fork is no longer used, thanks for the feedback and suggestion.
