### ISSUE TITLE
zint Aztec barcode bug

### ISSUE THREAD

**Issue by cfwsoft** [zint/zint-gpl-only#67]
Aztec barcode Encode bug Abnormal program crashes, it seems that the endless loop

**Comment by mikemaikaefer** [comment]
1. this is not the latest ZINT repository, this is an outdate fork only, the original can be found at sourceforge.net

2. this is a completely useless bugreport, nobody could reproduce anything with this

**Comment by gitlost** [comment]
The latest version of Zint does not seem to suffer from this issue, though there were issues in the past with Aztec Code. Am closing this as this fork is no longer used. Please raise a ticket at https://sourceforge.net/p/zint/tickets/ if you've any further feedback, thanks.
