### ISSUE TITLE
Zint crashes on 'Sequence Export' when 'End Value' is 99999999

### ISSUE THREAD

**Issue by rajeeshknambiar** [zint/zint-gpl-only#68]
Click on '123...' button, enter 'End Value' as 99999999 and then click 'Create', CPU usage goes high and after a few minutes, zint crashes.

**Comment by gitlost** [comment]
Hi the latest version of Zint does not suffer from this issue (checks for large values were added), so am closing this. This fork is no longer in use so please raise any further feedback at https://sourceforge.net/p/zint/tickets/, thanks.
