### ISSUE TITLE
[FEAT] Automatically adjust 'Format' length based on 'End Value' in 'Sequence Export'

### ISSUE THREAD

**Issue by rajeeshknambiar** [zint/zint-gpl-only#69]
Feature request:
On the 'Sequence Export' window, adjust the number of '$' in 'Format' field based on the number of digits in 'End Value'.

**Comment by gitlost** [comment]
Hi, thanks for the suggestion. I've opened the issue on SourceForge at https://sourceforge.net/p/zint/tickets/264/, please see there for further info. Am closing this now as this fork is no longer in use but the SourceForge issue will remain open until implemented (or rejected!). Thanks for the suggestion.
