### ISSUE TITLE
[HELP] possibility to adjust x-dimension under CLI?

### ISSUE THREAD

**Issue by ghiewa** [zint/zint-gpl-only#70]
note,
The x-dimension of a symbol is size (usually the width) of the smallest element. For a linear symbology this is the width of the smallest bar. The default size of the x-dimension in a raster image is 2 pixels. Many symbologies have a fixed width-to-height ratio where the height is expressed as a multiple of the x-dimension.

is there any possibility have this params CLI command?

**Comment by oehhar** [comment]
Am 01.08.2018 um 09:51 schrieb Moyan:
> note,
> The x-dimension of a symbol is size (usually the width) of the smallest
> element. For a linear symbology this is the width of the smallest bar.
> The default size of the x-dimension in a raster image is 2 pixels. Many
> symbologies have a fixed width-to-height ratio where the height is
> expressed as a multiple of the x-dimension.
> 
> is there any possibility have this params CLI command?

Moyan,

thank you for the message !

IMHO, a height to module size ("module" is the standard name of your
term "x-dimension") ratio is only useful for the EAN symbology family,
and there is always a range.
In consequence, a fix ratio may not lead to real use cases, which want
to fill a certain space.

It is possible to implement this in the CLI. Robin may comment, if he is
interested in implementing it. As an alternative, you may provide the
implementation.

Thank you and best regards,
Harald

**Comment by gitlost** [comment]
Hi, perhaps I'm misunderstanding but the `--scale` option in the CLI will adjust the X-dimension for you. Am closing this as this fork is no longer in use but if you've any further questions please raise a ticket at https://sourceforge.net/p/zint/tickets/ or subscribe to the SourceForge mailing list, thanks.
