### ISSUE TITLE
What is needed to build zint-qt on Ubuntu

### ISSUE THREAD

**Issue by MagnetoOptical** [zint/zint-gpl-only#71]
I see this question come up a lot, but haven't found an answer in the documentation I've found so far, the mailing list (which is pretty sparse), or here.

I've successfully built the CLI binary for 2.4.2.  I don't get any errors or any indication that anything is missing.
I did the following:
Cloned git
```
cd zint
mkdir build
cd build
cmake ..
make -j 96
sudo make install
```

It builds instantaneously without errors.
Am I missing an argument or switch for make to get zint-qt to build?
(NOTE: '-j 96' is appropriate for my system; this is not recommended for most)

**Comment by ProfElectric** [comment]
I should have mentioned, but didn't, that I have libqt4-dev installed.

**Comment by sunk818** [comment]
@ProfElectric Maybe you can update your initial instructions with dependencies to install before hand. No harm if it is installed already, but could make it easier for others. 

Also for `make -j ` -- I've read that number is usually based on number of threads and memory you have available. 96 seems a bit high to me, but maybe for zint it is okay...

https://unix.stackexchange.com/questions/208568/how-to-determine-the-maximum-number-to-pass-to-make-j-option

**Comment by gitlost** [comment]
Hi there is detailed documentation now on building on Linux at https://sourceforge.net/p/zint/code/ci/master/tree/README.linux, also for Windows at https://sourceforge.net/p/zint/code/ci/master/tree/win32/README and macOS at https://sourceforge.net/p/zint/code/ci/master/tree/README.macos.

Am closing this now as this fork is no longer in use but if you've any further questions please raise a ticket at https://sourceforge.net/p/zint/tickets/ or subscribe to the mailing list, thanks.
