### ISSUE TITLE
[Bug] numeric compaction mode in pdf417

### ISSUE THREAD

**Issue by ambikaverma** [zint/zint-gpl-only#72]
It seems that the encoder is not entering numeric encoding mode for PDF417 encoder.

In function - quelmode(char codeascii) the if condition for **TEXT** mode -

if ((codeascii == '\t') || (codeascii == '\n') || (codeascii == '\r') || ((codeascii >= ' ') && (codeascii <= '~'))) { mode = TEX; }

is **satisfied** even when data is a sequence of numbers and the **next condition** for numeric mode is not checked - 

else if((codeascii >= '0') && (codeascii <= '9')) { mode = NUM; }

**Comment by oehhar** [comment]
Dear Ambikaverma,

thank you for your bug report.
The currently maintained version of zint is at:

https://sourceforge.net/projects/zint/

You may consider to check, if your fix is already included there.
If not, you may consider to issue a ticket there.

Best regards,
Harald

**Comment by gitlost** [comment]
Hi, the PDF417 encoder in the latest version of Zint does enter numeric compaction mode for various inputs. If you've a specific example that doesn't when it should, please raise a ticket at https://sourceforge.net/p/zint/tickets/ and it will be dealt with. Am closing this now as this fork is no longer in use, thanks.
