### ISSUE TITLE
Error in online guide for PDF417 options

### ISSUE THREAD

**Issue by ocgltd** [zint/zint-gpl-only#74]
I think the online guide is wrong (or confusing) in regards to PDF417 error correction.  I have reproduced the text from the website here:

> The width of the generated PDF417 symbol can be specified at the command line using the --cols switch followed by a number between 1 and 30, and the amount of check digit information can be specified by using the --security switch followed by a number between 0 and 8 where the number of codewords used for check information is determined by 2^(value + 1). If using the API these values are assigned to option_2 and option_1 respectively.

I interpret this to mean that I can set the option1 value to any number from 0 through 8.  However, upon experimenting it seems only values from 0 to 2 will generate barcodes (using the API).  Using the formula above 2^(0+1)= and 2^(2+1)=8, so perhaps the input value must be between 0 and 2, not 0 and 8?  (0-8 is the output of the calculation).

**Comment by oehhar** [comment]
Thank you for this great post.

May you please double-check that the only up-to date manual is the text file coming with the source or the binary distributions in the doc folder ?
There was also a correction in the latest release on this point also in qzint.
You may consider to check the latest version.

Both may be obtained in the zint sourceforge project.

Thank you,
Harald

**Comment by ocgltd** [comment]
I was using the online documentation (http://zint.org.uk/Manual.aspx?type=p&page=6)

I have not checked the documentation packaged with the latest download...so if that's newer then consider this post just a notice that the online doc is confusing

**Comment by oehhar** [comment]
Yes, confusion is a common experience in Open source. There are multiple forks of zint.
Thank you for making clear where you got your information from.
This helps due to potential confusion on this side...

**Comment by gitlost** [comment]
Hi I believe the security option works as documented for PDF417 in the latest version of Zint. If you don't think it does or you've any further feedback, please raise a ticket at https://sourceforge.net/p/zint/tickets/ as this fork is no longer used, thanks!
