### ISSUE TITLE
move Releases to https://github.com/zint/zint/releases

### ISSUE THREAD

**Issue by blackcrack** [zint/zint-gpl-only#75]
Hi,

why do you not move you working Releases to :
 https://github.com/zint/zint/releases

?

best Regards
Blacky

**Comment by oehhar** [comment]
Hi Blacky,

thank you for the proposition.
The zint branch on github is maintained by other people who do their own
releases. It is not related.

Best regards,
Harald

Am 12.04.2020 um 09:39 schrieb blackcrack:
> Hi,
> 
> why do you not move you working Releases tu :
> https://github.com/zint/zint/releases
> 
> ?
> 
> best Regards
> Blacky

**Comment by blackcrack** [comment]
a github download is more better as on the "automaated" "you have take this f... popup" 
bull... from Sourceforge.., there is the normal download from the releases more better.

if you want not change your download to github or if this not important enough, clouse this issue..

best regards
Blacky

**Comment by oehhar** [comment]
Dear Blacky,

thank you for your proposal. Remark that there are a lot of forks of
zint. You are refering to one of them. If you want the version of zint
on sourceforge, you should take that version.
If you want the version on github (which is another fork), then use that
version.

Thank you,
Harald

Am 14.04.2020 um 12:23 schrieb blackcrack:
> a github download is more better as on the "automaated" "you have take
> this f... popup"
> bull... from Sourceforge.., there is the normal download from the
> releases more better.
> 
> if you want not change your download to github or if this not important
> enough, clouse this issue..
> 
> best regards
> Blacky

**Comment by oehhar** [comment]
I deleted my posts after checking the background. Sorry for the noise.

You may remark that this repository and its content is quite old.

A zint 2.8.0 release happend at sourceforge 2020-04-10. If you are interested in this release,  please go to the sourceforge site.

Thank you,
Harald

**Comment by blackcrack** [comment]
well refresh you it, that's not the problem, you be the Owner about your own code ;)  
and it was not a noise.. the noise is the sourceforge by download youre binarys in zipfile,  
the real problem is Sourceforge's download automatic with reload pages very long download url's   and so on.. this make the whole very noisy  ..
Harald Öhleman, wir können auch auf deutsch quatschen, iss vielleicht besser *g*

liebe Grüße
Blacky

**Comment by gitlost** [comment]
Hi, Zint is remaining on SourceForge but hopefully downloading from there isn't that big of an issue. However we may consider adding releases to the github mirror at https://github.com/zint/zint in the future as you suggest. If you've any further feedback or suggestions, please raise a ticket at https://sourceforge.net/p/zint/tickets/ as this fork is no longer in use, thanks.
