### ISSUE TITLE
PDF417 error in generated barcode

### ISSUE THREAD

**Issue by ocgltd** [zint/zint-gpl-only#77]
I'm investigating why PDF417 barcodes I create with ZINT aren't being accepted by some of our security scanners.  I noticed a very subtle difference in the barcode generated by our label printer (and software) and the one generated by zint.  I have attached an example.

The number of columns and rows is identical, and the start and stop columns (1 and 5) look identical.  However, notice how col 2 starts to look different in the ZINT barcode?  

I should point out that both barcodes scan fine on my test scanner and cell phone scanner and both decode to the same number, but the security scanners are rejecting the zint barcode.  I *assume* that there is a bug in zint causing the different barcode.  Can someone confirm the bug ?  (And hopefully resolve)

In case it matters, I'm using these settings
```
m_symbol->option_1 = 2;  // 4 word ecc (I think 2^2)
m_symbol->option_2 = 3;  // 3 col + start + stop
```

FYI: I tried to recreate the problem in Zint Barcode Studio 2.4 but that generates another (3rd) different barcode - as shown below.  Even with the same settings as above.  
![studio-barcode](https://user-images.githubusercontent.com/669986/88486715-c30c0e00-cf4d-11ea-9000-86dd28f8c22f.jpg)

So I also tried a bunch of online (web) based barcode generators, and I'm suprised to find everyone seems to come up with a different barcode!  Is there perhaps a parameters I need to set to bring above (first two) barcodes into alignment?

**Comment by ocgltd** [comment]
Based on another issue raised, I see there is an optional check byte ("--secure").  Could that be the cause?

Also, could the above barcode be switching from Text to Numeric midway through the encoded string?

**Comment by gitlost** [comment]
Hi, if you could provide more detail e.g. what you expect versus you get then we may be able to help you. In any case this fork is no longer in use so please raise a ticket at https://sourceforge.net/p/zint/tickets/ if you've still got an issue and can provide more detail, thanks.
