### ISSUE TITLE
libpng-dev is required

### ISSUE THREAD

**Issue by serge2016** [zint/zint-gpl-only#79]
Hello.

This is required before installation:
```sudo apt install libpng-dev```

**Comment by gitlost** [comment]
Hi, thanks, yes the documentation has been updated to reflect this, see for instance the [manual](https://sourceforge.net/p/zint/code/ci/master/tree/docs/manual.txt) Section 2.1 Linux. As this fork is no longer in use am closing this. If you've any further feedback please raise a ticket at https://sourceforge.net/p/zint/tickets/, thanks.
