### ISSUE TITLE
Please add the ability to right click and copy the code as an image.

### ISSUE THREAD

**Issue by Joe23232** [zint/zint-gpl-only#80]
Whether it'd be barcode or QR code, I am unable to right click and copy the code as an image. Please add the ability to right click and copy the QR code as an image or any other code.

Additionally I wish to suggest a setting which automatically copies the image to the clipboard as soon as I paste the link (or text).

**Comment by gitlost** [comment]
Hi, right-clicking to save to the clipboard in various formats is now supported in the latest version of Zint. I'm dubious about your second suggestion as overwriting the clipboard unbidden isn't usually considered "good form". However if you think it's a good idea please open a ticket at https://sourceforge.net/p/zint/tickets/ and it will be considered, thanks!
