### ISSUE TITLE
Data Matrix encoding issue

### ISSUE THREAD

**Issue by MSBluhm** [zint/zint-gpl-only#85]
Hi there,

my colleague and I are currently working on a layouting software
and we use Zint to visualize barcodes.

When trying different contents in the Data Matrix (DMC)
noticed that the optimal calculation in conjunction with the
Base256 encoding is faulty.

Version used: 2.10.0
Example:

     DMC size: 18x18
     value: öööhelloworld123456
     bytes: 18
     character: 19
    
     DMC size: 18x18
     value: helloworld1234567890ööö
     bytes: 18
     characters: 23
    
We have found that in the first case the
Base256 encoding up to the "w" and
only then does the change to ASCII.

Shouldn't the Base256 encoding end after
the third "ö" to get the optimal character length?

![ZintImageFailure](https://user-images.githubusercontent.com/98893763/152177487-c6fcacca-d9dc-4530-a790-931c7c7c6599.png)
![ZintImageOptimum](https://user-images.githubusercontent.com/98893763/152177492-7bcb43d0-067e-4b1b-a7c0-0c4764146054.png)
![ZintImageWithoutFailure](https://user-images.githubusercontent.com/98893763/152177493-f9816b82-6a45-4315-bbf2-26f32e8ad8c9.png)

**Comment by gitlost** [comment]
Hi thanks for reporting this. This fork is not in use - if you open a ticket on the source forge site https://sourceforge.net/p/zint/tickets/ then it will be seen by the developers, thanks.

**Comment by gitlost** [comment]
Hi trying the first example "öööhelloworld123456" in the latest version of Zint it does encode as you suggest, ending the Base256 encodation after the third "ö", i.e. "BBBTTTTTTTTTAAAAAAA". The optimization method for Data Matrix was fairly recently changed to use a Dijkstra-based algorithm which should give optimal (or near optimal) results so it's likely you were using an earlier version of Zint. If this is still an issue or you've any further feedback, please see previous comment, thanks, am closing now.
