### ISSUE TITLE
"Data to encode" line experience

### ISSUE THREAD

**Issue by DmitryP4** [zint/zint-gpl-only#86]
Could you consider some improvements here?
It would probably make the usage more convenient:

- A button to clear the "Data to encode" line;
- A checkbox to clear the line on restart;
- Slightly increased line height.

Thank you for the nice app!

**Comment by gitlost** [comment]
Hi thanks for your feedback. This fork is not in use - if you open a ticket on the source forge site https://sourceforge.net/p/zint/tickets/ then it will be seen by the developers, thanks.

**Comment by gitlost** [comment]
Hi, thanks very much for the suggestions. The first one has been implemented in the latest source and will be available in the next release. I've opened a ticket at https://sourceforge.net/p/zint/tickets/265/ to track this and your further suggestions. Please reply there if you've any further feedback, am closing this now (see previous comment), thanks.
