### ISSUE TITLE
QR Code not readable when Background is 'BLACK' and Foreground is 'White'...

### ISSUE THREAD

**Issue by aiamuzz** [zint/zint-gpl-only#87]
Hi,

I have just installed your wonderful application and testing it. 

When i changed the Background to **'Black'** and the foreground to **'White'** the QR Code is not readable the **QR Code mobile apps**

**Zint generated QR Codes :**

**URL :** https://www.aakziom.com/fun-campaigns

Zint default QR Code ...
![BlackONWhite-FunCampaigns](https://user-images.githubusercontent.com/3283676/171995452-a1b12147-bdfc-49d1-b06d-56edf769d042.png)

Zint BlackBG QR Code ... **(THIS IS NOT READABLE, YOU CAN TRY SCANNING IT)**
![WhiteONBlack-FunCampaigns](https://user-images.githubusercontent.com/3283676/171995457-ea14921c-48a5-4027-8cc6-8dc421dbb4e4.png)

Am i missing some setting that will enable a Dark Background QR Code to be readable just fine as the standard white background QR codes ?

Looking forward to your response ...

thanks.

**Comment by aiamuzz** [comment]
However the QR code I generate from the online service, reads the QR codes with both the White Background and Black Background ones just fine.

https://www.the-qrcode-generator.com/ 

the-qrcode-generator (default QR Code)
![the-qrcode-generator-Black on White](https://user-images.githubusercontent.com/3283676/171995274-10f452c4-f19d-434e-8149-2ae554812951.png)

the-qrcode-generator (BlackBG QR Code)
![the-qrcode-generator-White on Black](https://user-images.githubusercontent.com/3283676/171995282-fb71d4f6-f228-4712-bd5f-014d898bf31c.png)

Please find a small video i recorded on this website, please see how the QRCode keeps switching between various backgrounds ...

![Record_select-area_20220604154149](https://user-images.githubusercontent.com/3283676/171995335-43750072-6bf7-4ae9-a4fa-10b6bf4282e1.gif)

I think its a small adjustment that needs to be factored when Backgrounds are switched just like how the-qrcode-generator website as accomodated.

Look forward to being able to generate Black Background QR codes as our product surface on which the QR codes will be printed are black...

thanks.

**Comment by aiamuzz** [comment]
Please find the above 'decoded' ... The default black-on-white QR Code should be reversed and the corners(same demonstrated in the video below) welded to the reversed code.

if you want to add this as an option/feature ... just add the following entry to your current UI under the 'Appearance' tab ...

- [ ]  Reverse to Dark Background

If the above is checked than the following operations should effect ...

![Record_select-area_20220604165941](https://user-images.githubusercontent.com/3283676/171997266-1debd405-3e57-4160-9037-76d46b190f6f.gif)

**Comment by aiamuzz** [comment]
@g3rrk ... @ismaell  & @trevor ... 

look forward to this feature ...

if the QR code is not constructed as i've observed above then your Appearance Tab and the feature it consists where one can change the 'Background and Foreground Colors' will be dysfunctional**(with the QR Code rendered unreadable)** with the colors serving no purpose other than cosmetic. A colorful QR Code but a dysfunctional QR Code is a misnomer in itself.

**Comment by gitlost** [comment]
This was opened on SourceForge at https://sourceforge.net/p/zint/tickets/259/ and is marked as resolved, so am closing this. If you've any further feedback please comment on the SourceForge ticket or open a new one, thanks for the feedback.
